/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizacao;

import javax.swing.JOptionPane;

/**
 *
 * @author GABS
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        esqueciMinhaSenha = new javax.swing.JLabel();
        entrar_bt = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        userInput = new javax.swing.JTextField();
        passwdInput = new javax.swing.JPasswordField();
        pw_txt = new javax.swing.JLabel();
        user_txt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        login_txt = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        esqueciMinhaSenha.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        esqueciMinhaSenha.setForeground(new java.awt.Color(51, 51, 51));
        esqueciMinhaSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        esqueciMinhaSenha.setText("Esqueci minha senha");
        esqueciMinhaSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esqueciMinhaSenhaMouseClicked(evt);
            }
        });
        getContentPane().add(esqueciMinhaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, -1, -1));

        entrar_bt.setBackground(new java.awt.Color(237, 237, 237));
        entrar_bt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        entrar_bt.setForeground(new java.awt.Color(51, 51, 51));
        entrar_bt.setText("Entrar");
        entrar_bt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        entrar_bt.setPreferredSize(new java.awt.Dimension(135, 37));
        entrar_bt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrar_btmouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entrar_btmouseExited(evt);
            }
        });
        entrar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar_btActionPerformed(evt);
            }
        });
        getContentPane().add(entrar_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 180, 40));

        cancelButton.setBackground(new java.awt.Color(237, 237, 237));
        cancelButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(51, 51, 51));
        cancelButton.setText("Cancelar");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelButtonmouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelButtonmouseExited(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 180, 40));

        userInput.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userInput.setForeground(new java.awt.Color(102, 102, 102));
        userInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        userInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputActionPerformed(evt);
            }
        });
        getContentPane().add(userInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 320, 50));

        passwdInput.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        passwdInput.setForeground(new java.awt.Color(102, 102, 102));
        passwdInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        getContentPane().add(passwdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 320, 50));

        pw_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        pw_txt.setForeground(new java.awt.Color(51, 51, 51));
        pw_txt.setText("Senha");
        getContentPane().add(pw_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 320, 30));

        user_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        user_txt.setForeground(new java.awt.Color(51, 51, 51));
        user_txt.setText("Usuário");
        getContentPane().add(user_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 320, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_user_100px.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 100, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/covidd.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 580, 620));

        login_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 35)); // NOI18N
        login_txt.setForeground(new java.awt.Color(51, 51, 51));
        login_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_txt.setText("Login");
        getContentPane().add(login_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 280, -1));

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/loginV2.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 1020, 771));

        setSize(new java.awt.Dimension(932, 657));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInputActionPerformed

    private void esqueciMinhaSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esqueciMinhaSenhaMouseClicked
        /**
        * recuperar a senha
        *
        */
    }//GEN-LAST:event_esqueciMinhaSenhaMouseClicked

    private void entrar_btmouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrar_btmouseEntered
     
    }//GEN-LAST:event_entrar_btmouseEntered

    private void entrar_btmouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrar_btmouseExited
     
    }//GEN-LAST:event_entrar_btmouseExited

    private void entrar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar_btActionPerformed
   
        if(userInput.getText().equals("Covid19")&&passwdInput.getText().equals("1234")){
          
    MenuPrincipal tela = new MenuPrincipal();
    tela.setVisible(true);
    dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Senha ou Usuário Invalidos");
        }
        
    }//GEN-LAST:event_entrar_btActionPerformed

    private void cancelButtonmouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonmouseEntered
        
    }//GEN-LAST:event_cancelButtonmouseEntered

    private void cancelButtonmouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonmouseExited
      
    }//GEN-LAST:event_cancelButtonmouseExited

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
       System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton entrar_bt;
    private javax.swing.JLabel esqueciMinhaSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel login_txt;
    private javax.swing.JPasswordField passwdInput;
    private javax.swing.JLabel pw_txt;
    private javax.swing.JTextField userInput;
    private javax.swing.JLabel user_txt;
    // End of variables declaration//GEN-END:variables
}
