/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizacao;

/**
 *
 * @author GABS
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonInfermeiro = new javax.swing.JButton();
        jButtonMedico = new javax.swing.JButton();
        jButtonVacina = new javax.swing.JButton();
        jButtonMais = new javax.swing.JButton();
        jButtonAgenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonFecharBenvindo = new javax.swing.JButton();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRegistar = new javax.swing.JMenu();
        jMenuItemMedico = new javax.swing.JMenuItem();
        jMenuItemPaciente = new javax.swing.JMenuItem();
        jMenuItemAcompanhante = new javax.swing.JMenuItem();
        jMenuItemConsulta = new javax.swing.JMenuItem();
        jMenuItemVacina = new javax.swing.JMenuItem();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jMenuItemteste = new javax.swing.JMenuItem();
        jMenuItemVentilador = new javax.swing.JMenuItem();
        jMenuItemQuarentena = new javax.swing.JMenuItem();
        jMenuItemInfermeiro = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemFuncionario = new javax.swing.JMenuItem();
        jMenuItemIlha = new javax.swing.JMenuItem();
        jMenuItemLaboratorio = new javax.swing.JMenuItem();
        jMenuItemHospital = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuFeramenta = new javax.swing.JMenu();
        jMenuItemMenuBemVindo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrameBemVindo.setTitle("Bem Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 90, 40));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agenda");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 170, 80, 30));

        jButtonInfermeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/nurse_1.png"))); // NOI18N
        jButtonInfermeiro.setToolTipText("Infermeiro");
        jButtonInfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfermeiroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInfermeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 60, 70));

        jButtonMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/doctor_1.png"))); // NOI18N
        jButtonMedico.setToolTipText("Médico");
        jButtonMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 70, 70));

        jButtonVacina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/vaccine_1.png"))); // NOI18N
        jButtonVacina.setToolTipText("Vacina");
        jPanel1.add(jButtonVacina, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 60, 70));

        jButtonMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/plus.png"))); // NOI18N
        jButtonMais.setToolTipText("Registar Mais");
        jPanel1.add(jButtonMais, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 60, 70));

        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/note.png"))); // NOI18N
        jButtonAgenda.setToolTipText("Agendamento");
        jPanel1.add(jButtonAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 60, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Covid-Ideies.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-610, -50, 1380, 440));

        jInternalFrameBemVindo.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 740, 330));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Sistema de Gerenciamento de:");
        jInternalFrameBemVindo.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        jButtonFecharBenvindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/close (1).png"))); // NOI18N
        jButtonFecharBenvindo.setToolTipText("Fechar Tela Bem Vindo");
        jButtonFecharBenvindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharBenvindoActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(jButtonFecharBenvindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 30, 30));

        getContentPane().add(jInternalFrameBemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 770, 420));

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 460));

        jMenuRegistar.setText("Registar");

        jMenuItemMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/doctor.png"))); // NOI18N
        jMenuItemMedico.setText("Médicos");
        jMenuItemMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedicoActionPerformed(evt);
            }
        });
        jMenuRegistar.add(jMenuItemMedico);

        jMenuItemPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/pacient.png"))); // NOI18N
        jMenuItemPaciente.setText("Pacientes");
        jMenuRegistar.add(jMenuItemPaciente);

        jMenuItemAcompanhante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/employees.png"))); // NOI18N
        jMenuItemAcompanhante.setText("Acompanhante");
        jMenuRegistar.add(jMenuItemAcompanhante);

        jMenuItemConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/diagnosis.png"))); // NOI18N
        jMenuItemConsulta.setText("Consulta");
        jMenuRegistar.add(jMenuItemConsulta);

        jMenuItemVacina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/vaccine.png"))); // NOI18N
        jMenuItemVacina.setText("Vacina");
        jMenuRegistar.add(jMenuItemVacina);

        jMenuItemFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/route.png"))); // NOI18N
        jMenuItemFornecedor.setText("Fornecedor");
        jMenuRegistar.add(jMenuItemFornecedor);

        jMenuItemteste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/testing.png"))); // NOI18N
        jMenuItemteste.setText("Teste");
        jMenuItemteste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemtesteActionPerformed(evt);
            }
        });
        jMenuRegistar.add(jMenuItemteste);

        jMenuItemVentilador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/hospital-bed.png"))); // NOI18N
        jMenuItemVentilador.setText("Ventilador");
        jMenuRegistar.add(jMenuItemVentilador);

        jMenuItemQuarentena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/icon (1).png"))); // NOI18N
        jMenuItemQuarentena.setText("Quarentena");
        jMenuRegistar.add(jMenuItemQuarentena);

        jMenuItemInfermeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/nurse.png"))); // NOI18N
        jMenuItemInfermeiro.setText("Infermeiro");
        jMenuItemInfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInfermeiroActionPerformed(evt);
            }
        });
        jMenuRegistar.add(jMenuItemInfermeiro);

        jMenuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/profile.png"))); // NOI18N
        jMenuItemUsuario.setText("Usuarios");
        jMenuRegistar.add(jMenuItemUsuario);

        jMenuItemFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/employee.png"))); // NOI18N
        jMenuItemFuncionario.setText("Funcionário");
        jMenuRegistar.add(jMenuItemFuncionario);

        jMenuItemIlha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/earth-globe.png"))); // NOI18N
        jMenuItemIlha.setText("Ilha");
        jMenuRegistar.add(jMenuItemIlha);

        jMenuItemLaboratorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/lab.png"))); // NOI18N
        jMenuItemLaboratorio.setText("Laboratório");
        jMenuRegistar.add(jMenuItemLaboratorio);

        jMenuItemHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/hospital.png"))); // NOI18N
        jMenuItemHospital.setText("Hospital");
        jMenuRegistar.add(jMenuItemHospital);

        jMenuBar1.add(jMenuRegistar);

        jMenuRelatorio.setText("Relatórios");
        jMenuBar1.add(jMenuRelatorio);

        jMenuFeramenta.setText("Feramentas");

        jMenuItemMenuBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/home-page.png"))); // NOI18N
        jMenuItemMenuBemVindo.setText("Tela Bem-Vindo");
        jMenuItemMenuBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMenuBemVindoActionPerformed(evt);
            }
        });
        jMenuFeramenta.add(jMenuItemMenuBemVindo);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/covid-19.png"))); // NOI18N
        jMenuItem1.setText("Informação");
        jMenuFeramenta.add(jMenuItem1);

        jMenuBar1.add(jMenuFeramenta);

        jMenuSair.setText("Sair");

        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/icons8-sair-24.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(869, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedicoActionPerformed
      FormMedico tela = new FormMedico();
      tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemMedicoActionPerformed

    private void jMenuItemtesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemtesteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemtesteActionPerformed

    private void jButtonFecharBenvindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharBenvindoActionPerformed
      jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonFecharBenvindoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemMenuBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMenuBemVindoActionPerformed
       MenuPrincipal tela = new MenuPrincipal();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_jMenuItemMenuBemVindoActionPerformed

    private void jButtonMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicoActionPerformed
      FormMedico tela = new FormMedico();
      tela.setVisible(true);
    }//GEN-LAST:event_jButtonMedicoActionPerformed

    private void jButtonInfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfermeiroActionPerformed
      FormInfereiro tela = new FormInfereiro();
      tela.setVisible(true);
    }//GEN-LAST:event_jButtonInfermeiroActionPerformed

    private void jMenuItemInfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInfermeiroActionPerformed
      FormInfereiro tela = new FormInfereiro();
      tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemInfermeiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonFecharBenvindo;
    private javax.swing.JButton jButtonInfermeiro;
    private javax.swing.JButton jButtonMais;
    private javax.swing.JButton jButtonMedico;
    private javax.swing.JButton jButtonVacina;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFeramenta;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAcompanhante;
    private javax.swing.JMenuItem jMenuItemConsulta;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemFuncionario;
    private javax.swing.JMenuItem jMenuItemHospital;
    private javax.swing.JMenuItem jMenuItemIlha;
    private javax.swing.JMenuItem jMenuItemInfermeiro;
    private javax.swing.JMenuItem jMenuItemLaboratorio;
    private javax.swing.JMenuItem jMenuItemMedico;
    private javax.swing.JMenuItem jMenuItemMenuBemVindo;
    private javax.swing.JMenuItem jMenuItemPaciente;
    private javax.swing.JMenuItem jMenuItemQuarentena;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenuItem jMenuItemVacina;
    private javax.swing.JMenuItem jMenuItemVentilador;
    private javax.swing.JMenuItem jMenuItemteste;
    private javax.swing.JMenu jMenuRegistar;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
